import SiteHeader from "./components/ui/SiteHeader";
import { Analytics } from "@vercel/analytics/react"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="da">
			<body className={inter.className}>
				<SiteHeader />
				{children}
			</body>
			<Analytics/>
		</html>
	);
}
